In [1]:
from src.hosp_forecast import main_parallel
from src import paths
import os
import pandas as pd
import numpy as np

In [2]:
beta_forecast_path = os.path.join(
    paths.OUTPUT_DIR, "trend_forecast_test", "2023-12-09", "b_t_fct_boot.csv"
)
forecasted_betas = pd.read_csv(beta_forecast_path)
forecast_betas = forecasted_betas.to_numpy()
forecast_betas = forecast_betas.T

In [3]:
forecast_betas[0].shape

(28,)

In [4]:
main_parallel.main(
    forecasted_betas=forecast_betas,
    location_code="04",
    reference_date="2023-12-09",
    use_nbinom=False,
)

Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)


In [7]:
forecast_file_path = os.path.join(paths.HOSP_OUTPUT_DIR, '2023-12-09', '04-PMCMC-flu-predictions.csv')
forecast_df = pd.read_csv(forecast_file_path)

In [8]:
forecast_df

reference_date  horizon target_end_date  location output_type  \
0      2023-12-09        4      2023-12-16         4    quantile   
1      2023-12-09        4      2023-12-16         4    quantile   
2      2023-12-09        4      2023-12-16         4    quantile   
3      2023-12-09        4      2023-12-16         4    quantile   
4      2023-12-09        4      2023-12-16         4    quantile   
..            ...      ...             ...       ...         ...   
87     2023-12-09        1      2024-01-06         4    quantile   
88     2023-12-09        1      2024-01-06         4    quantile   
89     2023-12-09        1      2024-01-06         4    quantile   
90     2023-12-09        1      2024-01-06         4    quantile   
91     2023-12-09        1      2024-01-06         4    quantile   

    output_type_id  value  
0            0.010    131  
1            0.025    135  
2            0.050    137  
3            0.100    140  
4            0.150    141  
..             ...    ...  
87           0.850    142  
88           0.900    142  
89           0.950    143  
90           0.975    144  
91           0.990    144  

[92 rows x 7 columns]

In [9]:
target_dates = pd.read_csv('../datasets/target_dates.csv')

In [20]:
dates = target_dates.to_numpy()
dates[0][0]

'2023-10-14'

In [21]:
# Generate forecasts for all dates
# for the recent Trend Forecast test on Arizona

for date in dates:
    date = date[0]
    beta_forecast_path = os.path.join(
        paths.OUTPUT_DIR, "trend_forecast_test", date, "b_t_fct_boot.csv"
    )
    try:
        forecasted_betas = pd.read_csv(beta_forecast_path)
        forecast_betas = forecasted_betas.to_numpy()
        forecast_betas = forecast_betas.T
    except FileNotFoundError:
        continue
        
    main_parallel.main(
        forecasted_betas=forecast_betas,
        location_code="04",
        reference_date=date,
        use_nbinom=False,
    ) 

Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)
Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)
Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)
Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)
Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Bootstraps: 400
All Forecasts Shape: (400, 5, 28)


all_forecasts: (400, 28)
Starting.
[7.1063215e+06 2.3107966e+03 4.2737125e+04 1.3256873e+02 9.4229688e+03]
Data loaded.
Number Boo

In [22]:
import os
import shutil

# Define your paths
parent_folder = paths.HOSP_OUTPUT_DIR  # The folder containing all the subfolders (dates)
output_folder = os.path.join(parent_folder, 'test_predictions_20241006')  # Where all the renamed CSVs will be stored

# Create output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Loop through each subfolder (which are named by date)
for subfolder in os.listdir(parent_folder):
    subfolder_path = os.path.join(parent_folder, subfolder)

    # Check if it's a directory
    if os.path.isdir(subfolder_path):
        # Find the CSV file in the subfolder
        for file in os.listdir(subfolder_path):
            if file.endswith('.csv'):
                csv_file_path = os.path.join(subfolder_path, file)
                
                # Rename the file with the subfolder's name (date)
                new_filename = f"{subfolder}-hosp-forecasts.csv"
                new_file_path = os.path.join(output_folder, new_filename)

                # Copy (or move) the file to the output folder with the new name
                shutil.copy(csv_file_path, new_file_path)
                print(f"Copied and renamed {csv_file_path} to {new_file_path}")


Copied and renamed /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/2023-12-09/04-PMCMC-flu-predictions.csv to /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/test_predictions_20241006/2023-12-09-hosp-forecasts.csv
Copied and renamed /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/2023-10-28/04-PMCMC-flu-predictions.csv to /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/test_predictions_20241006/2023-10-28-hosp-forecasts.csv
Copied and renamed /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/2023-11-04/04-PMCMC-flu-predictions.csv to /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/test_predictions_20241006/2023-11-04-hosp-forecasts.csv
Copied and renamed /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/2023-11-11/04-PMCMC-flu-predictions.csv to /home/andrew/PycharmProjects/pmcmc_forecast/output/hosp_forecast/test_predictions_20241006/2023-11-11-hosp-forecasts.csv
Copied a